sudo: required

virtualenv:
  system_site_packages: true

language: python
python:
  - "2.7"

# command to install dependencies
install:
  - curl -o psycopg2.tar.gz http://initd.org/psycopg/tarballs/PSYCOPG-2-6/psycopg2-2.6.1.tar.gz
  - pip install psycopg2.tar.gz
  - pip install -r static/requirements.txt
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
