os: ubuntu
sudo: required

virtualenv:
  system_site_packages: true

language: python
python:
  - "2.7"

# Start PostgreSQL
services:
  - postgresql

# command to install dependencies
install:
  - pip install -r static/requirements.txt

# Create a database for my application
before_script:
  - psql -c 'create database testdb;' -U postgres 

# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
