sudo: required

virtualenv:
  system_site_packages: true

language: python
python:
  - "2.7"

# command to install dependencies
install:
  - sudo apt-get install postgresql
  - sudo apt-get install python-psycopg2
  - sudo apt-get install libpq-dev
  - pip install -r static/requirements.txt
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
