os: ubuntu
sudo: required

virtualenv:
  system_site_packages: true

language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r static/requirements.txt

# Start PostgreSQL
services:
  - postgresql

# Create a database for my application
before_script:
  -psql -c 'create database travis_ci_test;' -U postgres

# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
